import { LivestockType } from "@/types/api-types";

export const livestockSource: LivestockType[] = [
  {
    id: "1",
    name: "#8201",
    slug: "8201",
    currentPrice: "0.2 ETH",
    lastSellPrice: "0.18 ETH",
    owner: "cryptofarmer",
    timeListed: "12 days ago",
  },
  {
    id: "2",
    name: "#4303",
    slug: "4303",
    currentPrice: "0.2 ETH",
    lastSellPrice: "0.18 ETH",
    owner: "chizaalabs",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "#4301",
    slug: "4301",
    currentPrice: "0.2 ETH",
    lastSellPrice: "0.18 ETH",
    owner: "web3clubs",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "#2301",
    slug: "2301",
    currentPrice: "0.2 ETH",
    lastSellPrice: "0.18 ETH",
    owner: "cryptofarmer",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "#8201",
    slug: "8201",
    currentPrice: "0.2 ETH",
    lastSellPrice: "0.18 ETH",
    owner: "cryptofarmer",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "#8201",
    slug: "8201",
    currentPrice: "0.2 ETH",
    lastSellPrice: "0.18 ETH",
    owner: "cryptofarmer",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "#8201",
    slug: "8201",
    currentPrice: "0.2 ETH",
    lastSellPrice: "0.18 ETH",
    owner: "cryptofarmer",
    timeListed: "12 days ago",
  },  {
    id: "1",
    name: "#8201",
    slug: "8201",
    currentPrice: "0.2 ETH",
    lastSellPrice: "0.18 ETH",
    owner: "cryptofarmer",
    timeListed: "12 days ago",
  },
];
