import { PenType } from "@/types/api-types";

export const penSource: PenType[] = [
  {
    id: "12",
    name: "Farmers Group Pens (FGP)",
    slug: "farmers-group-pens-fgp",
    tvl: "$223.63m",
    farmerRevenue: "$223.63m",
    gardenRevenue: "$745.89m",
    platformRevenue: "$630.37m",
  },
  {
    id: "12",
    name: "Local Herders Pens (LHP)",
    slug: "local-herders-pens-lhp",
    tvl: "$63.41m",
    farmerRevenue: "$63.41m",
    gardenRevenue: "$63.41m",
    platformRevenue: "$400.75m",
  },
  {
    id: "12",
    name: "Helga Community Pens (FGP)",
    slug: "helga-community-pens-fgp",
    tvl: "$132.68m",
    farmerRevenue: "$132.68m",
    gardenRevenue: "$132.68m",
    platformRevenue: "$199.98m",
  },
  {
    id: "12",
    name: "Masaku Livestock Farmers (FGP)",
    slug: "masaku-livestock-farmers-fgp",
    tvl: "$745.89m",
    farmerRevenue: "$745.89m",
    gardenRevenue: "$745.89m",
    platformRevenue: "$2.19b",
  },
  {
    id: "12",
    name: "Mwangi Family Pens (FGP)",
    slug: "mwangi-family-pens-fgp",
    tvl: "$18.88m",
    farmerRevenue: "$18.88m",
    gardenRevenue: "$745.89m",
    platformRevenue: "$106.53m",
  },
  {
    id: "12",
    name: "Local Herders Pens (FGP)",
    slug: "local-herders-pens-fgp",
    tvl: "$745.89m",
    farmerRevenue: "$745.89m",
    gardenRevenue: "$745.89m",
    platformRevenue: "$2.19b",
  },
  {
    id: "12",
    name: "Farmers Group Pens (FGP)",
    slug: "farmers-group-pens-fgp",
    tvl: "$223.63m",
    farmerRevenue: "$223.63m",
    gardenRevenue: "$745.89m",
    platformRevenue: "$630.37m",
  },
  {
    id: "12",
    name: "Local Herders Pens (LHP)",
    slug: "local-herders-pens-lhp",
    tvl: "$63.41m",
    farmerRevenue: "$63.41m",
    gardenRevenue: "$63.41m",
    platformRevenue: "$400.75m",
  },
  {
    id: "12",
    name: "Helga Community Pens (FGP)",
    slug: "helga-community-pens-fgp",
    tvl: "$132.68m",
    farmerRevenue: "$132.68m",
    gardenRevenue: "$132.68m",
    platformRevenue: "$199.98m",
  },
  {
    id: "12",
    name: "Masaku Livestock Farmers (FGP)",
    slug: "masaku-livestock-farmers-fgp",
    tvl: "$745.89m",
    farmerRevenue: "$745.89m",
    gardenRevenue: "$745.89m",
    platformRevenue: "$2.19b",
  },
  {
    id: "12",
    name: "Mwangi Family Pens (FGP)",
    slug: "mwangi-family-pens-fgp",
    tvl: "$18.88m",
    farmerRevenue: "$18.88m",
    gardenRevenue: "$745.89m",
    platformRevenue: "$106.53m",
  },
];
